### ISSUE TITLE
Suggestion: A way to turn of the Eclipse Artifact from the menu 

### ISSUE THREAD

**Issue by WolfgangIsBestWolf** [William758/ZetArtifacts#1]
Or just having it so it disappears automatically if EclipseMultiplayer is installed. Since it disappears when DiluvianArtifact is installed it could be neat compatibility with the other Eclipse mod.

**Comment by William758** [comment]
It still makes sense for the artifact to be there because it would allow you to enable eclipse while using another difficulty like Typhoon at the same time.

**Comment by William758** [comment]
I've added configs to remove artifacts from the menu.
