### ISSUE TITLE
Tossing configs for all item tiers?

### ISSUE THREAD

**Issue by eGhpGZeMqhlAIRtA1soVFK4JCDnrsxAXjirz97L** [William758/ZetArtifacts#13]
Is it possible to implement configs for all item tiers to be droppable (not just blue, pink and worldunique)?
It would synergize extremely well with ShareSuite, as dropped items are otherwise infinitely duplicated in multiplayer.

**Comment by William758** [comment]
I've gone ahead and added a config for all item tiers. Although I think the artifact should probably just be disabled if you are using ShareSuite.
