### ISSUE TITLE
Artifact of Tossing - T1, T2 and T3 Config Issue

### ISSUE THREAD

**Issue by eGhpGZeMqhlAIRtA1soVFK4JCDnrsxAXjirz97L** [William758/ZetArtifacts#15]
dropifactT1, dropifactT2 or dropifactT3 settings also affect void items of the same rank, so for example disabling dropping for T1 and T2 items but enabling it for T3 and void items won't let you drop any void items except for Pluripotent Larva and Benthic Bloom.

**Comment by William758** [comment]
I've made it so those configs only effect the non-void item tiers and added configs for all the void item tiers.
