### ISSUE TITLE
Lose MiniRpcLib dependancy?

### ISSUE THREAD

**Issue by ZgSvDaCpke479pF6DzfLgMvK9AiyNsgUBKPghdh** [William758/ZetArtifacts#2]
Would it be possible for ZetArtifacts to eventually go without MiniRpcLib as a forced dependancy? It seems that a lot of other mods have undergone this change previously.

**Comment by William758** [comment]
Yeah, I'll look into using the networking added by R2API instead.

**Comment by William758** [comment]
The new networking seems to be working so I've uploaded an update.
