### ISSUE TITLE
Consider merging DiluvianArtifact into ZetArtifacts and add the option to disable specific artifacts in the config, aswell as one that lets the effect be active at all times?

### ISSUE THREAD

**Issue by ZgSvDaCpke479pF6DzfLgMvK9AiyNsgUBKPghdh** [William758/ZetArtifacts#4]
Merging them would mostly be for simplicity's sake, since both mods also share the same artifact at this time (Eclipse). Additionally, implementing an option to disable select artifacts from loading would be beneficial to those who are only looking for specific features to be added. Finally, if an artifact is active for every single run and 100% of the time it might aswell not be an artifact, but just a tweak, so an option that would just turn a specific artifact into a normal, all-time tweak would be great (such as those in your ZetTweaks mod). 

I've got this last idea from Blobface's "Future Plans" tab on his Artifact of the King, which he hasn't got around to yet. I don't think anyone who's done artifact mods has, in fact. The way I would approach it would be something like this: add a boolean setting that would Enable (default) or Disable an artifact from loading into the game entirely, then another which would make the artifact load as such by default or otherwise as a silent tweak, hidden from the artifacts tab.

**Comment by William758** [comment]
I want to keep DiluvianArtifact as its own thing as it was originally someone else's mod that I asked for permission to update.

As for the other request, yeah I think that's a good idea. I'll add some configs to hide or have an artifacts effect always active.

**Comment by William758** [comment]
I've just updated my artifact mods with configs to disable or always enable
