### ISSUE TITLE
Artifact of Progression

### ISSUE THREAD

**Issue by Yolad** [William758/ZetArtifacts#6]
There is an issue with the gold income when killing monsters that have evolved. 
If a monster has evolved and has been left unattended for a while after killing them you won't receive any gold. 
I have seen this issue happen mostly with monsters that evolved into boss mobs i.e beetle guard into beetle queen

**Comment by William758** [comment]
Artifact of Progression is from the Aetherium mod. I don't use this artifact but a quick look at the code shows that the evolved monsters should drop the same gold as the monster it evolved from.
