### ISSUE TITLE
Issue with Multitudes Artifact set to 0 (hide and never apply)

### ISSUE THREAD

**Issue by VarnaScelestus** [William758/ZetArtifacts#7]
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
FixPlayercount.FixPlayercount.ApplyZetMultitudesArtifact (System.Int32 origPlayerCount) (at <9498d8ac9722423db08e99b932ec7f21>:IL_0006)
FixPlayercount.FixPlayercount.GetConnectedPlayers () (at <9498d8ac9722423db08e99b932ec7f21>:IL_005F)
FixPlayercount.FixPlayercount.GetParticipatingPlayerCountHook (RoR2.Run self) (at <9498d8ac9722423db08e99b932ec7f21>:IL_0001)
DMD<>?1316905728.Hook<RoR2.Run::get_participatingPlayerCount>?453279744 (RoR2.Run ) (at <1e17f47f3ac645d99216d44d368f2d42>:IL_0000)
RoR2.Run.RecalculateDifficultyCoefficentInternal () (at <9cd64984fa244ad6be9ff1fde41ed978>:IL_0020)
RoR2.Run.RecalculateDifficultyCoefficent () (at <9cd64984fa244ad6be9ff1fde41ed978>:IL_0000)
RoR2.Run.OnFixedUpdate () (at <9cd64984fa244ad6be9ff1fde41ed978>:IL_0000)
RoR2.Run.FixedUpdate () (at <9cd64984fa244ad6be9ff1fde41ed978>:IL_002D)

This error spams the console whenever the artifact is set to disabled in the config. It also causes monsters to never spawn and the stage timer to be far left of the default starting position (and it never increments).

**Comment by William758** [comment]
Just let the mod author of FixPlayercount know so he can fix it.

**Comment by William758** [comment]
Latest version of FixPlayercount should fix the issue.
