### ISSUE TITLE
Multitudes Stops Voidling Spawning

### ISSUE THREAD

**Issue by GalacticRuler** [William758/ZetArtifacts#8]
[LogOutput.log](https://github.com/William758/ZetArtifacts/files/8194878/LogOutput.log)
Multitudes appears to be breaking the Voidling similar to how the original mod did with Mythrix* (*A guess on my part)

**Comment by GalacticRuler** [comment]
Might not be just Multitudes? Unsure, might be another mod's implementation of fake-players? (Bigger Bazaar adds an AI Artificer to buy, who counts towards player-count)

**Comment by William758** [comment]
I can't find anywhere else in the game code that would prevent spawning based on player count. I'll have to check and see if i can replicate the issue by going there.

**Comment by William758** [comment]
Just did the voidling fight with multitudes and didn't notice any issues. Maybe some other mod is interfering? I'll see if it is still fine with an ai artificer.

**Comment by William758** [comment]
Which mod adds a purchasable artificer? I don't see an option for it in Bigger Bazaar and Fetch a Friend doesn't add it.

**Comment by GalacticRuler** [comment]
Hm, sorry it took so long to get back to you
I'm not entirely sure! But whichever does add that, is the culprit. Multitudes works fine otherwise
