### ISSUE TITLE
Elites not spawning

### ISSUE THREAD

**Issue by Rexinator50** [William758/ZetArtifacts#9]
For some reason when I use the mod elites don't spawn. Tested with just this mod and the two it depends on, with different characters, and different artifact selections. I use r2modman to load them. It got to the point in later stages that almost no hostiles were spawning at all.

**Comment by William758** [comment]
I'm pretty sure that EliteAPI in R2API isn't working properly so I've disabled the feature using it.

**Comment by Rexinator50** [comment]
Fixed in latest update, thanks!
